-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 17:27:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sakila_datawh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila_datawh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sakila_datawh` DEFAULT CHARACTER SET latin1 ;
USE `sakila_datawh` ;

-- -----------------------------------------------------
-- Table `sakila_datawh`.`dim_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_datawh`.`dim_customer` (
  `customer_key` INT(8) NOT NULL AUTO_INCREMENT,
  `customer_last_update` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  `customer_id` INT(8) NULL DEFAULT NULL,
  `customer_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `customer_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `customer_active` CHAR(3) NULL DEFAULT NULL,
  `customer_address` VARCHAR(64) NULL DEFAULT NULL,
  `customer_district` VARCHAR(20) NULL DEFAULT NULL,
  `customer_city` VARCHAR(50) NULL DEFAULT NULL,
  `customer_country` VARCHAR(50) NULL DEFAULT NULL,
  `customer_valid_from` DATE NULL DEFAULT NULL,
  `customer_valid_through` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`customer_key`),
  INDEX `customer_id` USING BTREE (`customer_id`) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 601
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sakila_datawh`.`dim_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_datawh`.`dim_date` (
  `date_key` INT(8) NOT NULL,
  `date_value` DATE NOT NULL,
  `date_medium` CHAR(16) NOT NULL,
  `month_number` TINYINT(3) NOT NULL,
  `month_name` CHAR(12) NOT NULL,
  `year4` SMALLINT(5) NOT NULL,
  `year_month_number` CHAR(7) NOT NULL,
  PRIMARY KEY (`date_key`),
  UNIQUE INDEX `date` USING BTREE (`date_value`) VISIBLE,
  UNIQUE INDEX `date_value` (`date_value` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sakila_datawh`.`dim_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_datawh`.`dim_film` (
  `film_key` INT(8) NOT NULL AUTO_INCREMENT,
  `film_last_update` DATETIME NOT NULL,
  `film_title` VARCHAR(64) NOT NULL,
  `film_description` TEXT NOT NULL,
  `film_release_year` SMALLINT(5) NOT NULL,
  `film_language` VARCHAR(20) NOT NULL,
  `film_rental_duration` TINYINT(3) NULL DEFAULT NULL,
  `film_rental_rate` DECIMAL(4,2) NULL DEFAULT NULL,
  `film_duration` INT(8) NULL DEFAULT NULL,
  `film_replacement_cost` DECIMAL(5,2) NULL DEFAULT NULL,
  `film_rating_text` VARCHAR(30) NULL DEFAULT NULL,
  `film_id` INT(11) NOT NULL,
  `film_category` CHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`film_key`))
ENGINE = MyISAM
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sakila_datawh`.`dim_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_datawh`.`dim_staff` (
  `staff_key` INT(8) NOT NULL AUTO_INCREMENT,
  `staff_last_update` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  `staff_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `staff_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `staff_id` INT(8) NULL DEFAULT NULL,
  `staff_store_id` INT(8) NULL DEFAULT NULL,
  `staff_version_number` SMALLINT(5) NULL DEFAULT NULL,
  `staff_valid_from` DATE NULL DEFAULT NULL,
  `staff_valid_through` DATE NULL DEFAULT NULL,
  `staff_active` CHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`staff_key`),
  INDEX `staff_id` USING BTREE (`staff_id`) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sakila_datawh`.`dim_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_datawh`.`dim_store` (
  `store_key` INT(8) NOT NULL AUTO_INCREMENT,
  `store_last_update` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  `store_id` INT(8) NULL DEFAULT NULL,
  `store_address` VARCHAR(64) NULL DEFAULT NULL,
  `store_district` VARCHAR(20) NULL DEFAULT NULL,
  `store_city` VARCHAR(50) NULL DEFAULT NULL,
  `store_country` VARCHAR(50) NULL DEFAULT NULL,
  `store_manager_staff_id` INT(8) NULL DEFAULT NULL,
  `store_manager_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `store_manager_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `store_version_number` SMALLINT(5) NULL DEFAULT NULL,
  `store_valid_from` DATE NULL DEFAULT NULL,
  `store_valid_through` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`store_key`),
  INDEX `store_id` USING BTREE (`store_id`) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sakila_datawh`.`fact_rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_datawh`.`fact_rental` (
  `customer_key` INT(8) NOT NULL,
  `staff_key` INT(8) NOT NULL,
  `film_key` INT(8) NOT NULL,
  `store_key` INT(8) NOT NULL,
  `date_key` INT(8) NOT NULL,
  `count_returns` INT(10) NOT NULL,
  `count_rentals` INT(8) NOT NULL,
  `rental_id` INT(11) NULL DEFAULT NULL,
  INDEX `fk_customer_idx` (`customer_key` ASC) VISIBLE,
  INDEX `fk_stafk_idx` (`staff_key` ASC) VISIBLE,
  INDEX `fk_store_idx` (`store_key` ASC) VISIBLE,
  INDEX `fk_film_idx` (`film_key` ASC) VISIBLE,
  INDEX `fk_date_idx` (`date_key` ASC) VISIBLE,
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`customer_key`)
    REFERENCES `sakila_datawh`.`dim_customer` (`customer_key`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff`
    FOREIGN KEY (`staff_key`)
    REFERENCES `sakila_datawh`.`dim_staff` (`staff_key`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store`
    FOREIGN KEY (`store_key`)
    REFERENCES `sakila_datawh`.`dim_store` (`store_key`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film`
    FOREIGN KEY (`film_key`)
    REFERENCES `sakila_datawh`.`dim_film` (`film_key`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_date`
    FOREIGN KEY (`date_key`)
    REFERENCES `sakila_datawh`.`dim_date` (`date_key`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
